services:
  database:
    image: mariadb:11
    container_name: mariadb_franquicias
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: franquicias
      MARIADB_USER: app
      MARIADB_PASSWORD: secret
    ports:
      - "3380:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  app:
    build: .
    container_name: spring_franquicias
    restart: always
    depends_on:
      - database
    ports:
      - "8033:8033"
    environment:
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: "true"
    volumes:
      - .:/app
      - ~/.gradle:/home/gradle/.gradle
    working_dir: /app
    command: ["/bin/sh", "-c", "./gradlew build --continuous & sleep 5 && ./gradlew bootRun"]

volumes:
  mariadb_data:
